### ISSUE TITLE
Centralize discord user handling

### ISSUE THREAD

**Issue by AarKro** [AarKro/Hera-Chatbot#18]
Create a class dedicated to discord user handling.

This class resolves discord user IDs, discord user nickname IDs and plain text discord names and nicknames and returns an IUser object.
This way user handling is centralized and the same for every command. It also enforces user validation, since no IUser object is returned, if no user was found.

**Comment by Chromeroni** [comment]
Done with issue #45

**Comment by Chromeroni** [comment]
Nevermind, wrong issues... whoops.
