### ISSUE TITLE
Centralize user rights check

### ISSUE THREAD

**Issue by AarKro** [AarKro/Hera-Chatbot#24]
**Now**
Currently, the users rights are only checked if necessary and this in the command itself.

**Suggested change**
Extend the command interface with a method that checks if the user has enough permission. It takes a list containing the required permissions and the user as an IUser object as parameters.
This way, before a command is issued, a rights check can be initiated.

There needs to be a way to determin the needed rights for each command.
Possible solutions;
* Create properties file for permissions
* Extend BotCommand Enum, it now holds a List containing the required rights
* Predefine the required rights for each command in the command classes themselves.

**Prerequisite**
Issue #18

**Comment by Chromeroni** [comment]
Done with issue #45
