### ISSUE TITLE
KMS Function for Hera

### ISSUE THREAD

**Issue by MCPGamer** [AarKro/Hera-Chatbot#44]
A Function that lets the Discord user commit suicide

**Comment by Chromeroni** [comment]
Just one question ... why?

**Comment by Chromeroni** [comment]
also how on earth is this an enhancement.

**Comment by MCPGamer** [comment]
1st y not?
2nd clearly its a better bot if it actually gives you the chance to commit suicide

**Comment by MCPGamer** [comment]
my classmate agrees

**Comment by MCPGamer** [comment]
we now learning scrum btw

**Comment by Chromeroni** [comment]
... what would it do tho?

Also this is not a platform for casual conversation.

**Comment by Pacmens** [comment]
Yes it is

**Comment by Chromeroni** [comment]
no staph
