### ISSUE TITLE
Implement database from database concept

### ISSUE THREAD

**Issue by AarKro** [AarKro/Hera-Chatbot#68]
**Describe the current situation / your motivation for the change**
Hera currently stores all of its data in property files or not at all.

**Describe the solution you'd like**
Setup a database based on the database concept created in #59 using MySQL through Heras web server.

**Comment by AarKro** [comment]
Database can be found in the web server control panel --> phpMyAdmin.

The aaronkromer prefixes were necessary because it is the name of the web disk account.

**Comment by Pacmens** [comment]
Relations and tables look good so far. They need specifictation of nullable modifiers though.

**Comment by AarKro** [comment]
Fields role#parent and module_settings#roleFK are now nullable.
